name: Build & Deploy Vite to Hostinger

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Si tes secrets sont dans un Environment, dé-commente:
    # environment: production

    env:
      FTP_SERVER: ${{ secrets.FTP_SERVER }}
      FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      FTP_PORT: ${{ secrets.FTP_PORT }}
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          for v in FTP_SERVER FTP_USERNAME FTP_PASSWORD FTP_PORT VITE_SUPABASE_URL VITE_SUPABASE_ANON_KEY; do
            if [ -z "${!v}" ]; then echo "❌ Missing secret: $v"; exit 1; fi
          done
          echo "✅ All required secrets are present."

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (clean)
        run: npm ci

      - name: Build Vite
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ env.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ env.VITE_SUPABASE_ANON_KEY }}

      - name: Smoke check (index exists)
        run: test -f dist/index.html

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ env.FTP_SERVER }}
          username: ${{ env.FTP_USERNAME }}
          password: ${{ env.FTP_PASSWORD }}
          port: ${{ env.FTP_PORT }}
          protocol: ftps
          server-dir: public_html/   # ✅ cible directement ton site
          local-dir: dist/           # ✅ envoie seulement le contenu du build
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/.htaccess
