name: Build & Deploy to VPS

on:
  push:
    tags:
      - 'v*'               # déploiement uniquement sur tag v*
  workflow_dispatch: {}     # déclenchement manuel possible

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  build-and-deploy:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 20
      REMOTE_HOST: ${{ secrets.VPS_HOST }}
      REMOTE_USER: ${{ secrets.VPS_USER }}
      REMOTE_PORT: ${{ secrets.VPS_PORT }}
      REMOTE_PATH: ${{ secrets.VPS_PATH }}      # ex: /var/www/notionlab
      VERSION: ${{ github.ref_name }}           # ex: v1.2.3
      NGINX_RELOAD: ${{ secrets.NGINX_RELOAD }} # 'true' ou 'false'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Sécurité : le tag doit pointer sur main
      - name: Ensure tag is on main
        shell: bash
        run: |
          git fetch origin main --depth=1
          git merge-base --is-ancestor "$(git rev-parse origin/main)" "$GITHUB_SHA" \
            || { echo "❌ Le tag doit pointer sur un commit de main"; exit 1; }

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (inject env)
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: npm run build

      - name: Prepare SSH key
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p "${REMOTE_PORT:-22}" "${REMOTE_HOST}" >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        shell: bash
        run: |
          RSYNC_FLAGS="-az --delete --chmod=D755,F644"
          rsync $RSYNC_FLAGS -e "ssh -i ~/.ssh/id_ed25519 -p ${REMOTE_PORT:-22}" \
            dist/ "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}/"

      - name: Reload Nginx (optional)
        if: ${{ env.NGINX_RELOAD == 'true' }}
        shell: bash
        run: |
          ssh -i ~/.ssh/id_ed25519 -p ${REMOTE_PORT:-22} \
            "${REMOTE_USER}@${REMOTE_HOST}" \
            'sudo nginx -t && sudo systemctl reload nginx || true'
