name: Build & Deploy Vite to VPS

on:
  push:
    tags: ['v*']          # même déclencheur que l'ancien
  workflow_dispatch:      # exécution manuelle possible

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          req=(VPS_HOST VPS_USER VPS_PATH SSH_PRIVATE_KEY VITE_SUPABASE_URL VITE_SUPABASE_ANON_KEY)
          for v in "${req[@]}"; do
            [ -n "${{ secrets[$v] }}" ] || { echo "❌ Missing secret: $v"; exit 1; }
          done
          echo "✅ All required secrets are present."

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps (clean)
        run: npm ci

      - name: Build Vite
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: npm run build

      - name: Smoke check (index exists)
        run: test -f dist/index.html

      # ==== Déploiement SSH/rsync ====
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trust host (add VPS to known_hosts)
        run: ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure remote directory
        run: ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p '${{ secrets.VPS_PATH }}'"

      - name: Rsync dist -> VPS (clean-slate)
        run: |
          rsync -avz --delete \
            dist/ \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:'${{ secrets.VPS_PATH }}'

      - name: Post-deploy smoke check
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "test -f '${{ secrets.VPS_PATH }}/index.html'"
          echo "✅ Deployed $GITHUB_SHA"

